all: 1d bt bt_dfs star center1d center1ddfs

bt: bt.cpp
	g++ bt.cpp -o bt -std=c++11 
bt_dfs: bt_dfs.cpp
	g++ bt_dfs.cpp -o bt_dfs -std=c++11 
1d: 1d.cpp
	g++ 1d.cpp -o 1d -std=c++11 
center1d: center1d.cpp
	g++ center1d.cpp -o center1d -std=c++11 
center1ddfs: center1ddfs.cpp
	g++ center1ddfs.cpp -o center1ddfs -std=c++11 
star: star.cpp
	g++ star.cpp -o star -std=c++11 
clean:
	rm 1d bt bt_dfs star center1d center1ddfs
